/**
 * This file was automatically generated by the Mule Cloud Connector Development Kit
 */
package mx.maleficarum.memcached;

import org.mule.tools.cloudconnect.annotations.Connector;
import org.mule.tools.cloudconnect.annotations.Operation;

@Connector(namespacePrefix="memcached")
public class MemcachedCloudConnector {
    
    @Operation
    public void sendMessage(String key, Object message) {
    }
    
    @Operation
    public Object getMessage(String key) {
    	return null;
    }
}
