/**
 * This file was automatically generated by the Mule Cloud Connector Development Kit
 */
package mx.maleficarum.memcached;

import groovy.json.JsonBuilder;
import groovy.json.JsonSlurper;

import java.net.InetSocketAddress;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Map;

import net.spy.memcached.BinaryConnectionFactory;

import org.mule.api.annotations.Connect;
import org.mule.api.annotations.param.Optional;
import org.mule.tools.cloudconnect.annotations.Connector;
import org.mule.tools.cloudconnect.annotations.Operation;
import org.mule.tools.cloudconnect.annotations.Property;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@Connector(namespacePrefix="memcached")
public class MemcachedCloudConnector {
	
	private InetSocketAddress[] servers = null; //new InetSocketAddress[]{ new InetSocketAddress("127.0.0.1", 11211) };
	protected net.spy.memcached.MemcachedClient mc = null;
	
	@Property
	private String host;
	
	@Property
	private Integer timeToForget = 3600;
	
	@Property
	private Integer port ;
	
	private final Logger L = LoggerFactory.getLogger(MemcachedCloudConnector.class);
	
	@Connect
	public void connect() {
		try {
			servers = new InetSocketAddress[]{ new InetSocketAddress( host , port) };
			mc = new net.spy.memcached.MemcachedClient(new BinaryConnectionFactory(), new ArrayList<InetSocketAddress>(Arrays.asList(servers)));
			L.info("Connecting to {}:{}", host, port);
		} catch(Exception e) {
			e.printStackTrace();
		}
	}	
    
    @Operation
    public Object send(String key, Object payload) {
		
		if(mc == null) {
			this.connect();
			L.warn("Not connected to memcached ... connecting...");
		}
		
		if(mc != null) {
			JsonBuilder builder = new  JsonBuilder(payload);
			mc.set(key, timeToForget, builder.toString());
			L.info("Saving {} as {}", builder.toString(), key);
		} else {
			L.error("Unable to connect to memcached ...");
		}
		
		
		return payload;    	
    }
    
    @Operation
    public Map<String, Object> receive(String key) {	
    	Map<String, Object> map = null;
    	
		if(mc != null) {
			Object object = mc.get(key);

			if(object != null) {
				JsonSlurper parser = new JsonSlurper();
				
				parser.parseText((String) object);
			}
		}
		
		return map;
    }

	public String getHost() {
		return host;
	}

	public void setHost(String host) {
		this.host = host;
	}

	public Integer getTimeToForget() {
		return timeToForget;
	}

	public void setTimeToForget(Integer timeToForget) {
		this.timeToForget = timeToForget;
	}

	public Integer getPort() {
		return port;
	}

	public void setPort(Integer port) {
		this.port = port;
	}
    
    
}
